[package]
name = "consolesweeper"
version = "0.1.0"
authors = ["Master0r0/SarahGreyWolf <m.sarahgreywolf@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
